---
title: "First Draft"
date: "4/26/2022"
output: html_document
---

```{r}
library(ggplot2)
```

## read and visualize data set
```{r warning = F}
df = read.csv("merge.tsv", sep = '\t',header= F)
colnames(df) <- c("product_category","ratio","length","star_rating")
df$star_rating = factor(df$star_rating)
df$product_category = factor(df$product_category)
head(df)
```
## Data Set Statistics 
```{r}
summary(df)
```

## Remove extreme outliers of length 
greater than $Q_1-3*IQ$, less than $Q_3 + 3*IQ$
```{r}
upper = quantile(df$length)[4] + 3*(quantile(df$length)[4] - quantile(df$length)[2])
lower = quantile(df$length)[2] - 3*(quantile(df$length)[4] - quantile(df$length)[2])
df = df[(df$length>lower)&(df$length<upper),]
```

```{r, fig.width=3, fig.height=2, echo = F}
ggplot(df, aes(x=length))+
  geom_histogram(bins = 20,color="darkblue", fill="lightblue")+
  ggtitle("Length Histogram")
```

```{r, fig.width=3, fig.height=2, echo = F}
ggplot(df, aes(x=ratio))+
  geom_histogram(bins = 20,color="darkblue", fill="lightblue")+
  ggtitle("Ratio Histogram")
```


## Create a new variable `star1` and `star2`
```{r}
df = transform(df,star1=ifelse((star_rating==4)|(star_rating==5), "high","low"))
df$star1 = factor(df$star1)
df$star1 = relevel(df$star1,"low")
df = transform(df,star2=ifelse((star_rating==1)|(star_rating==5), "extreme","not extreme"))
df$star2 = factor(df$star2)
df$star2 = relevel(df$star2,"not extreme")
```

### Model 1
Estimated Model: $logit(\hat{\pi}) = 0.378 -0.003length + 0.751ratio + 0.003length * ratio$

```{r}
model1 = glm(star1 ~ length * ratio , data = df, family = "binomial")
summary(model1)
```

### Model 2
Estimated Model: $logit(\hat{\pi}) = 0.378 -0.003length + 0.751ratio + 0.003length * ratio$
```{r}
model2 = glm(star2 ~ length * ratio , data = df, family = "binomial")
summary(model2)
```


# odds estimator and confidence interval
```{r}
wald = confint.default(object = model2, level = 0.95)
est_df = cbind(exp(model2$coefficients),exp(wald))
est_df
```








## can be removed if no space left
```{r, fig.width=3, fig.height=2}

ggplot(df, aes(x=product_category))+
  geom_bar(color="darkblue", fill="lightblue")+
  ggtitle("Product Category Barplot")+
  theme(axis.text.x = element_text(angle = 90, hjust=0))
```


```{r, fig.width=3, fig.height=2, echo = F}
ggplot(df, aes(x=star_rating))+
  geom_bar(color="darkblue", fill="lightblue")+
  ggtitle("Star Rating Histogram")
```
