universe = vanilla

log    =    log/$(filename).log
error  =  error/$(filename).err
output = output/$(filename).out

executable = ./job.sh
arguments = $(filename)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = https://s3.amazonaws.com/amazon-reviews-pds/tsv/$(filename).tsv.gz, http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, job.R

request_cpus = 1
request_memory = 3GB   
request_disk = 3.5GB  

queue filename from files.txt
