---
title: "Untitled"
author: "Sherry Yang"
date: "5/6/2022"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
```


```{r}
df = read.csv("merge.tsv", sep = '\t',header= F)
colnames(df) <- c("product_category","ratio","length","star_rating")
upper = mean(df$length) + 3*sd(df$length) 
lower = mean(df$length) - 3*sd(df$length) 
df = df[(df$length>lower)&(df$length<upper),]
```

```{r, fig.width=6, fig.height=4}
df = transform(df,star1=ifelse((star_rating==4)|(star_rating==5), "high","low"))
df$star1 = factor(df$star1)
df$star1 = relevel(df$star1,"low")
model1 = glm(star1 ~ length * ratio , data = df, family = "binomial")
summary(model1)
predict1 = expand.grid(ratio = seq(from=0, to=1, by=.05), length = seq(min(df$length),max(df$length),by = 3))
predict1$predicted_prob = predict(model1, predict1, type="response")
ggplot(predict1, aes(length, predicted_prob, color=factor(ratio), group=ratio)) +
  geom_line()+
  ggtitle("The Probability of High Star Rating")+
  geom_hline(yintercept=0.5, color = "blue", size = 1.5)
```

```{r, fig.width=6, fig.height=4}
df = transform(df,star2=ifelse((star_rating==1)|(star_rating==5), "extreme","not extreme"))
df$star2 = factor(df$star2)
df$star2 = relevel(df$star2,"not extreme")
model2 = glm(star2 ~ length * ratio , data = df, family = "binomial")
summary(model2)
predict2 = expand.grid(ratio = seq(from=0, to=1, by=.05), length = seq(min(df$length),max(df$length),by = 3))
predict2$predicted_prob = predict(model2, predict2, type="response")
ggplot(predict2, aes(length, predicted_prob, color=factor(ratio), group=ratio)) +
  geom_line()+
  ggtitle("The Probability of Extreme Star Rating")+
  geom_hline(yintercept=0.5, color = "green", size = 1.5)
```
