universe = vanilla

log    =    log/$(Process).log
error  =  error/$(Process).err
output = output/$(Process).out

executable = ./job.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(Process).tsv, http://proxy.chtc.wisc.edu/SQUID/chtc/R402.tar.gz, job.R

request_cpus = 1
request_memory = 10GB #this needs to be revised
request_disk = 10GB   #this needs to be revised

queue 13
